apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -staging

# Staging-specific configurations
replicas:
  - name: redis-replica
    count: 2
  - name: postgres
    count: 2
  - name: mysql
    count: 2
  - name: mongodb
    count: 2
  - name: zookeeper
    count: 3
  - name: kafka
    count: 2
  - name: otel-collector
    count: 2
  - name: kiali
    count: 1
  - name: fastapi-app
    count: 2
