apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: greenfield
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-lb"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "greenfield"
  MYSQL_HOST: "mysql-lb"
  MYSQL_PORT: "3306"
  MYSQL_USER: "mysql"
  MYSQL_DB: "greenfield"
  MONGODB_HOST: "mongodb-lb"
  MONGODB_PORT: "27017"
  MONGODB_USER: "admin"
  KAFKA_BROKERS: "kafka-lb:9092"
