apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - init-configmap.yaml
  - service.yaml
  - statefulset.yaml

secretGenerator:
  - name: postgres-secret
    literals:
      - password=changeme123
