apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-config.yaml
  - gateways.yaml
  # Uncomment the following lines to deploy example configurations
  # - virtualservices-example.yaml
  # - certificates-example.yaml
