apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - server-config.yaml
  - service.yaml
  - statefulset.yaml

secretGenerator:
  - name: mysql-secret
    literals:
      - root-password=rootpass123
      - password=changeme123
