apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenfield

resources:
  - oauth2-proxy
  - gateway
  - policies

# Keycloak is optional and enabled via overlays
# - keycloak
