apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenfield

resources:
  # Include base FastAPI app
  - ../../kustomize/base/fastapi-app
  # Add authentication
  - auth.yaml
