apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - datasources-configmap.yaml
  - dashboards-configmap.yaml
  - service.yaml
  - deployment.yaml

secretGenerator:
  - name: grafana-secret
    literals:
      - admin-password=admin123
