apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenfield

resources:
  - ../../base
  # Include Keycloak as primary IdP
  - ../../base/keycloak

configMapGenerator:
  - name: provider-info
    literals:
      - provider=keycloak
      - provider-type=oidc
      - mode=primary-idp

generatorOptions:
  disableNameSuffixHash: true
