apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenfield

resources:
  - namespace
  - redis
  - postgres
  - mysql
  - mongodb
  - kafka
  - otel-collector
  - jaeger
  - prometheus
  - grafana
  - fastapi-app
  # Note: Istio and sealed-secrets should be installed separately as cluster-wide components
