apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

# Dev-specific configurations
replicas:
  - name: redis-master
    count: 1
  - name: redis-replica
    count: 1
  - name: postgres
    count: 1
  - name: mysql
    count: 1
  - name: mongodb
    count: 1
  - name: zookeeper
    count: 1
  - name: kafka
    count: 1
  - name: otel-collector
    count: 1
  - name: prometheus
    count: 1
  - name: grafana
    count: 1
  - name: fastapi-app
    count: 1

